[ general ]
token = "" # Bot Token
prefix = "" # Bot Prefix
mongodb_url = "" # MongoDB URL
guild = "" # Deine Guild ID

[ id ]
client_id = "" # Die ID vom Bot
guild_id = "" # Deine Guild ID

[[ status ]]
name = "Nachrichten zählen." # Name der Richpresence
type = "PLAYING" # PLAYING, LISTENING, WATCHING

[[ status ]]
name = "Nachrichten an."
type = "WATCHING"